# Generated by Django 5.1.5 on 2025-02-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
